### ISSUE TITLE
Frends.Zip.ExtractArchive initial implementation

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.ZIP#1]
Create initial implementation for ExtractArchive task, using the community ZIP ExtractArchive task as baseline (https://github.com/CommunityHiQ/Frends.Community.Zip).

In addition:

- The task should have its own nuget (as opposed to having a generic zip package)
- The task has to have good unit test coverage, as zipping is something that can be automated
- No integration tests required besides just testing zipping in unit tests
- It would be nice to have some performance indication in the performance test section of the readme.
- Add SonarCube
- Add workflows

**Comment by Svenskapojkarna** [comment]
Task has been implemented. CI workflows created for the task.

**Comment by jefim** [comment]
Please add a task descriptions, otherwise it shows up as "Task Description" when trying to install it in FRENDS

**Comment by jefim** [comment]
Here is the todo list:
- README missing in repo root
- Need to target .NET 6 only
- Needs review of project properties, e.g. missing description
- Needs CHANGELOG.md in https://keepachangelog.com/en/1.0.0/ format
