### ISSUE TITLE
Frends.Zip.CreateArchive initial implementation

### ISSUE THREAD

**Issue by jefim** [FrendsPlatform/Frends.ZIP#2]
Create initial implementation for CreateArchive task, using the community ZIP CreateArchive task as baseline (https://github.com/CommunityHiQ/Frends.Community.Zip).

In addition:
- The task should have its own nuget (as opposed to having a generic zip package)
- The task has to have good unit test coverage, as zipping is something that can be automated
- No integration tests required besides just testing zipping in unit tests
- It would be nice to have some performance indication in the performance test section of the readme.
- We need to add and check SonarCube linting and warning on that
- Need to setup actions workflows

**Comment by Svenskapojkarna** [comment]
Task has been implemented with .NET Standard 2.0 and .NET 6 support. CI workflows for the task are also added.

**Comment by jefim** [comment]
Please add a task descriptions, otherwise it shows up as "Task Description" when trying to install it in FRENDS

**Comment by jefim** [comment]
Todo:

- README missing in repo root
- Need to target .NET 6 only
- Needs review of project properties, e.g. missing description
- Needs CHANGELOG.md in https://keepachangelog.com/en/1.0.0/ format
